spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: YX050709 #替换为PgAdmin中实际设置的密码

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
